# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'rake'

Dummy::Application.load_tasks

load "#{File.expand_path('../../..', __FILE__)}/lib/tasks/rails_temporary_data.rake"
